Repository oliverkruse10/skal-vi-videre-app, pull requests merged in 2024-12, with the labels that each got.

#2 igen har jeg ændret titel
  app/(tabs)/index.tsx
Labels: New

#3 test
  app/(tabs)/index.tsx
Labels: bug

#4 Testtitel
  app/index.tsx
Labels: New, Update

#5 Tilføjet lokation
  app.json
  app/index.tsx
  eas.json
  package-lock.json
  package.json
Labels: New

#6 Har gjort at man kan se sin lokation på google maps
  app.json
  app/index.tsx
  package-lock.json
  package.json
Labels: New
